apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: default
  name: dev-kustomization

resources:
  - ../../../backend
  - ../../../frontend
  - ../../../shared

namePrefix: dev-
nameSuffix: ""